# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('read', '0002_auto_20150202_1342'),
        ('programdb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('name', models.CharField(max_length=255, verbose_name=b'Cluster Name', blank=True)),
                ('create_date', models.DateTimeField(null=True, blank=True)),
                ('edit_date', models.DateTimeField(null=True, blank=True)),
            ],
            options={
                'ordering': ('name',),
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('country', models.CharField(max_length=255, verbose_name=b'Country Name', blank=True)),
                ('code', models.CharField(max_length=4, verbose_name=b'2 Letter Country Code', blank=True)),
                ('description', models.CharField(max_length=255, verbose_name=b'Description/Notes', blank=True)),
                ('create_date', models.DateTimeField(null=True, blank=True)),
                ('edit_date', models.DateTimeField(null=True, blank=True)),
            ],
            options={
                'ordering': ('country',),
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('name', models.CharField(max_length=255, verbose_name=b'District Name', blank=True)),
                ('create_date', models.DateTimeField(null=True, blank=True)),
                ('edit_date', models.DateTimeField(null=True, blank=True)),
            ],
            options={
                'ordering': ('name',),
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='MergeMap',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('from_column', models.CharField(max_length=255, blank=True)),
                ('to_column', models.CharField(max_length=255, blank=True)),
            ],
            options={
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('gaitid', models.CharField(unique=True, max_length=255, verbose_name=b'GAITID', blank=True)),
                ('name', models.CharField(max_length=255, verbose_name=b'Program Name', blank=True)),
                ('fundingstatus', models.CharField(max_length=255, verbose_name=b'Funding Status', blank=True)),
                ('description', models.CharField(max_length=765, verbose_name=b'Program Description', blank=True)),
                ('create_date', models.DateTimeField(null=True, blank=True)),
                ('edit_date', models.DateTimeField(null=True, blank=True)),
                ('country', models.ManyToManyField(to='programdb.Country')),
            ],
            options={
                'ordering': ('create_date',),
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='ProgramDashboard',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('project_proposal', models.IntegerField(null=True, blank=True)),
                ('project_proposal_approved', models.IntegerField(null=True, blank=True)),
                ('project_agreement', models.IntegerField(null=True, blank=True)),
                ('project_agreement_approved', models.IntegerField(null=True, blank=True)),
                ('project_completion', models.IntegerField(null=True, blank=True)),
                ('project_completion_approved', models.IntegerField(null=True, blank=True)),
                ('create_date', models.DateTimeField(null=True, blank=True)),
                ('edit_date', models.DateTimeField(null=True, blank=True)),
                ('program', models.ForeignKey(blank=True, to='programdb.Program', null=True)),
            ],
            options={
                'ordering': ('program',),
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='ProjectAgreement',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('profile_code', models.CharField(max_length=255, verbose_name=b'Profile Code', blank=True)),
                ('proposal_num', models.CharField(max_length=255, verbose_name=b'Proposal Number', blank=True)),
                ('date_of_request', models.DateTimeField(null=True, verbose_name=b'Date of Request', blank=True)),
                ('project_title', models.CharField(max_length=255, verbose_name=b'Project Title', blank=True)),
                ('project_type', models.CharField(max_length=255, verbose_name=b'Proposal Number', blank=True)),
                ('community_rep', models.CharField(max_length=255, verbose_name=b'Community Representative', blank=True)),
                ('community_rep_contact', models.CharField(max_length=255, verbose_name=b'Community Representative Contact', blank=True)),
                ('community_mobilizer', models.CharField(max_length=255, verbose_name=b'Community Mobilizer', blank=True)),
                ('prop_status', models.CharField(max_length=255, verbose_name=b'Proposal Status', blank=True)),
                ('rej_letter', models.TextField(verbose_name=b'Rejection Letter', blank=True)),
                ('project_code', models.CharField(max_length=255, verbose_name=b'Project Code', blank=True)),
                ('field_office', models.CharField(max_length=255, verbose_name=b'Office Name', blank=True)),
                ('cod_num', models.CharField(max_length=255, verbose_name=b'Project COD #', blank=True)),
                ('project_activity', models.CharField(max_length=255, verbose_name=b'Project Activity', blank=True)),
                ('account_code', models.CharField(max_length=255, verbose_name=b'Account Code', blank=True)),
                ('sub_code', models.CharField(max_length=255, verbose_name=b'Account Sub Code', blank=True)),
                ('community', models.CharField(max_length=255, verbose_name=b'Community', blank=True)),
                ('staff_responsible', models.CharField(max_length=255, verbose_name=b'MC Staff Responsible', blank=True)),
                ('partners', models.CharField(max_length=255, verbose_name=b'Partners', blank=True)),
                ('name_of_partners', models.CharField(max_length=255, verbose_name=b'Name of Partners', blank=True)),
                ('program_objectives', models.TextField(verbose_name=b'What Program Objectives does this help fulfill?', blank=True)),
                ('mc_objectives', models.TextField(verbose_name=b'What MC strategic Objectives does this help fulfill?', blank=True)),
                ('effect_or_impact', models.TextField(verbose_name=b'What is the anticipated effect of impact of this project?', blank=True)),
                ('expected_start_date', models.DateTimeField(blank=True)),
                ('expected_end_date', models.DateTimeField(blank=True)),
                ('beneficiary_type', models.CharField(max_length=255, verbose_name=b'Type of direct beneficiaries', blank=True)),
                ('num_direct_beneficiaries', models.CharField(max_length=255, verbose_name=b'Number of direct beneficiaries', blank=True)),
                ('total_estimated_budget', models.CharField(max_length=255, blank=True)),
                ('mc_estimated_budget', models.CharField(max_length=255, blank=True)),
                ('other_budget', models.CharField(max_length=255, blank=True)),
                ('estimation_date', models.DateTimeField(blank=True)),
                ('justification_background', models.TextField(verbose_name=b'General background and problem statement', blank=True)),
                ('justification_description_community_selection', models.TextField(verbose_name=b'Description of community selection criteria', blank=True)),
                ('description_of_project_activities', models.TextField(blank=True)),
                ('description_of_government_involvement', models.TextField(blank=True)),
                ('description_of_community_involvement', models.TextField(blank=True)),
                ('documentation_government_approval', models.FileField(upload_to=b'uploads', null=True, verbose_name=b'Upload Government Documentation of Approval', blank=True)),
                ('documentation_community_approval', models.FileField(upload_to=b'uploads', null=True, verbose_name=b'Upload Community Documentation of Approval', blank=True)),
                ('approved_by', models.ForeignKey(related_name='approving_agreement', blank=True, to=settings.AUTH_USER_MODEL, null=True)),
                ('checked_by', models.ForeignKey(related_name='checking', blank=True, to=settings.AUTH_USER_MODEL, null=True)),
                ('cluster', models.ForeignKey(blank=True, to='programdb.Cluster', null=True)),
                ('country', models.ForeignKey(to='programdb.Country')),
                ('district', models.ForeignKey(blank=True, to='programdb.District', null=True)),
                ('estimated_by', models.ForeignKey(related_name='estimating', blank=True, to=settings.AUTH_USER_MODEL, null=True)),
                ('program', models.ForeignKey(blank=True, to='programdb.Program', null=True)),
            ],
            options={
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='ProjectProposal',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('profile_code', models.CharField(max_length=255, verbose_name=b'Profile Code', blank=True)),
                ('proposal_num', models.CharField(max_length=255, verbose_name=b'Proposal Number', blank=True)),
                ('date_of_request', models.DateTimeField(null=True, verbose_name=b'Date of Request', blank=True)),
                ('project_title', models.CharField(max_length=255, verbose_name=b'Project Title', blank=True)),
                ('project_type', models.CharField(max_length=255, verbose_name=b'Proposal Number', blank=True)),
                ('community_rep', models.CharField(max_length=255, verbose_name=b'Community Representative', blank=True)),
                ('community_rep_contact', models.CharField(max_length=255, verbose_name=b'Community Representative Contact', blank=True)),
                ('community_mobilizer', models.CharField(max_length=255, verbose_name=b'Community Mobilizer', blank=True)),
                ('prop_status', models.CharField(max_length=255, verbose_name=b'Proposal Status', blank=True)),
                ('rej_letter', models.TextField(verbose_name=b'Rejection Letter', blank=True)),
                ('project_code', models.CharField(max_length=255, verbose_name=b'Project Code', blank=True)),
                ('project_description', models.TextField(verbose_name=b'Project Description', blank=True)),
                ('approval', models.BooleanField(default=b'0', verbose_name=b'Approval')),
                ('approval_remarks', models.CharField(max_length=255, verbose_name=b'Approval Remarks', blank=True)),
                ('device_id', models.CharField(max_length=255, verbose_name=b'Device ID', blank=True)),
                ('date_approved', models.DateTimeField(null=True, blank=True)),
                ('proposal_review', models.FileField(upload_to=b'uploads', null=True, verbose_name=b'Proposal Review', blank=True)),
                ('proposal_review_2', models.FileField(upload_to=b'uploads', null=True, verbose_name=b'Proposal Review Additional', blank=True)),
                ('today', models.DateTimeField(null=True, blank=True)),
                ('start_time', models.DateTimeField(null=True, blank=True)),
                ('end_time', models.DateTimeField(null=True, blank=True)),
                ('meta_instance_id', models.CharField(max_length=255, verbose_name=b'Meta Instance ID', blank=True)),
                ('meta_instance_name', models.CharField(max_length=255, verbose_name=b'Meta Instance Name', blank=True)),
                ('odk_id', models.CharField(max_length=255, verbose_name=b'ODK ID', blank=True)),
                ('odk_uuid', models.CharField(max_length=255, verbose_name=b'ODK UUID', blank=True)),
                ('odk_submission_time', models.DateTimeField(null=True, verbose_name=b'ODK Submission Time', blank=True)),
                ('odk_index', models.CharField(max_length=255, verbose_name=b'ODK Index', blank=True)),
                ('odk_parent_table_name', models.CharField(max_length=255, verbose_name=b'ODK Table Name', blank=True)),
                ('odk_tags', models.CharField(max_length=255, verbose_name=b'ODK Tags', blank=True)),
                ('odk_notes', models.CharField(max_length=255, verbose_name=b'ODK Notes', blank=True)),
                ('create_date', models.DateTimeField(null=True, verbose_name=b'Date Created', blank=True)),
                ('edit_date', models.DateTimeField(null=True, verbose_name=b'Last Edit Date', blank=True)),
                ('latitude', models.CharField(max_length=255, verbose_name=b'Latitude (Coordinates)', blank=True)),
                ('longitude', models.CharField(max_length=255, verbose_name=b'Longitude (Coordinates)', blank=True)),
                ('approval_submitted_by', models.ForeignKey(related_name='requesting', blank=True, to=settings.AUTH_USER_MODEL, null=True)),
                ('approved_by', models.ForeignKey(related_name='approving', blank=True, to=settings.AUTH_USER_MODEL, null=True)),
                ('cluster', models.ForeignKey(blank=True, to='programdb.Cluster', null=True)),
                ('country', models.ForeignKey(to='programdb.Country')),
                ('district', models.ForeignKey(blank=True, to='programdb.District', null=True)),
                ('program', models.ForeignKey(blank=True, to='programdb.Program', null=True)),
            ],
            options={
                'ordering': ('create_date',),
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('name', models.CharField(max_length=255, verbose_name=b'Province Name', blank=True)),
                ('create_date', models.DateTimeField(null=True, blank=True)),
                ('edit_date', models.DateTimeField(null=True, blank=True)),
                ('country', models.ForeignKey(to='programdb.Country')),
            ],
            options={
                'ordering': ('name',),
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('sector', models.CharField(max_length=255, verbose_name=b'Sector Name', blank=True)),
                ('create_date', models.DateTimeField(null=True, blank=True)),
                ('edit_date', models.DateTimeField(null=True, blank=True)),
            ],
            options={
                'ordering': ('sector',),
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Village',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('name', models.CharField(max_length=255, verbose_name=b'Village Name', blank=True)),
                ('create_date', models.DateTimeField(null=True, blank=True)),
                ('edit_date', models.DateTimeField(null=True, blank=True)),
                ('district', models.ForeignKey(to='programdb.District')),
            ],
            options={
                'ordering': ('name',),
            },
            bases=(models.Model,),
        ),
        migrations.AddField(
            model_name='projectproposal',
            name='province',
            field=models.ForeignKey(blank=True, to='programdb.Province', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='projectproposal',
            name='village',
            field=models.ForeignKey(blank=True, to='programdb.Village', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='projectagreement',
            name='project_proposal',
            field=models.ForeignKey(to='programdb.ProjectProposal'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='projectagreement',
            name='province',
            field=models.ForeignKey(blank=True, to='programdb.Province', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='projectagreement',
            name='reviewed_by',
            field=models.ForeignKey(related_name='reviewing', blank=True, to=settings.AUTH_USER_MODEL, null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='projectagreement',
            name='sector',
            field=models.ForeignKey(to='programdb.Sector', blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='projectagreement',
            name='village',
            field=models.ForeignKey(blank=True, to='programdb.Village', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='mergemap',
            name='project_proposal',
            field=models.ForeignKey(to='programdb.ProjectProposal'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='mergemap',
            name='read',
            field=models.ForeignKey(to='read.Read'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='district',
            name='province',
            field=models.ForeignKey(to='programdb.Province'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='cluster',
            name='district',
            field=models.ForeignKey(to='programdb.District'),
            preserve_default=True,
        ),
    ]
