# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('programdb', '0004_auto_20150202_1413'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('contributor', models.CharField(max_length=255, verbose_name=b'Contributor', blank=True)),
                ('description', models.CharField(max_length=255, verbose_name=b'Description of Contribution', blank=True)),
                ('value', models.CharField(max_length=255, verbose_name=b'Value of Contribution', blank=True)),
                ('actual', models.BooleanField(default=None, verbose_name=b'Is an Actual Contribution')),
                ('create_date', models.DateTimeField(null=True, blank=True)),
                ('edit_date', models.DateTimeField(null=True, blank=True)),
            ],
            options={
                'ordering': ('contributor',),
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Documentation',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('name', models.CharField(max_length=135, verbose_name=b'Name of Document')),
                ('documentation_type', models.CharField(max_length=135, verbose_name=b'Type (File, Photo or URL)')),
                ('description', models.CharField(max_length=255)),
                ('file_field', models.ImageField(null=True, upload_to=b'uploads', blank=True)),
                ('create_date', models.DateTimeField(null=True, blank=True)),
                ('edit_date', models.DateTimeField(null=True, blank=True)),
            ],
            options={
                'ordering': ('name',),
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='ProjectComplete',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('activity_code', models.CharField(max_length=255, null=True, verbose_name=b'Activity Code', blank=True)),
                ('project_name', models.CharField(max_length=255, null=True, verbose_name=b'Project Name', blank=True)),
                ('expected_start_date', models.DateTimeField(null=True, blank=True)),
                ('expected_end_date', models.DateTimeField(null=True, blank=True)),
                ('actual_start_date', models.DateTimeField(null=True, blank=True)),
                ('actual_end_date', models.DateTimeField(null=True, blank=True)),
                ('on_time', models.BooleanField(default=None)),
                ('no_explanation', models.TextField(null=True, verbose_name=b'If not on time explain delay', blank=True)),
                ('estimated_budget', models.CharField(max_length=255, null=True, verbose_name=b'Estimated Budget', blank=True)),
                ('actual_budget', models.CharField(max_length=255, null=True, verbose_name=b'Actual Budget', blank=True)),
                ('budget_variance', models.CharField(max_length=255, null=True, verbose_name=b'Budget Variance', blank=True)),
                ('explanation_of_variance', models.CharField(max_length=255, null=True, verbose_name=b'Explanation of variance', blank=True)),
                ('direct_beneficiaries', models.CharField(max_length=255, null=True, verbose_name=b'Actual Direct Beneficiaries', blank=True)),
                ('jobs_created', models.CharField(max_length=255, null=True, verbose_name=b'Number of Jobs Created', blank=True)),
                ('jobs_part_time', models.CharField(max_length=255, null=True, verbose_name=b'Part Time Jobs', blank=True)),
                ('jobs_full_time', models.CharField(max_length=255, null=True, verbose_name=b'Full Time Jobs', blank=True)),
                ('government_involvement', models.CharField(max_length=255, null=True, verbose_name=b'Government Involvement', blank=True)),
                ('capacity_built', models.CharField(max_length=255, null=True, verbose_name=b'What capacity was built to ensure sustainability?', blank=True)),
                ('issues_and_challenges', models.TextField(null=True, verbose_name=b'List any issues or challenges faced (include reasons for delays)', blank=True)),
                ('lessons_learned', models.TextField(null=True, verbose_name=b'Lessons learned', blank=True)),
                ('latitude', models.CharField(max_length=255, null=True, verbose_name=b'Latitude (Coordinates)', blank=True)),
                ('longitude', models.CharField(max_length=255, null=True, verbose_name=b'Longitude (Coordinates)', blank=True)),
                ('actual_contribution', models.ForeignKey(to='programdb.Contribution')),
                ('approved_by', models.ForeignKey(related_name='approving_agreement_complete', blank=True, to=settings.AUTH_USER_MODEL, null=True)),
                ('checked_by', models.ForeignKey(related_name='checking_complete', blank=True, to=settings.AUTH_USER_MODEL, null=True)),
                ('cluster', models.ForeignKey(blank=True, to='programdb.Cluster', null=True)),
                ('country', models.ForeignKey(to='programdb.Country')),
                ('district', models.ForeignKey(blank=True, to='programdb.District', null=True)),
                ('documentation', models.ForeignKey(blank=True, to='programdb.Documentation', null=True)),
                ('estimated_by', models.ForeignKey(related_name='estimating_complete', blank=True, to=settings.AUTH_USER_MODEL, null=True)),
                ('program', models.ForeignKey(blank=True, to='programdb.Program', null=True)),
                ('project_agreement', models.ForeignKey(to='programdb.ProjectAgreement')),
                ('project_proposal', models.ForeignKey(to='programdb.ProjectProposal')),
                ('province', models.ForeignKey(blank=True, to='programdb.Province', null=True)),
            ],
            options={
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='QuantitativeOutputs',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('number_achieved', models.CharField(max_length=255, verbose_name=b'Contributor', blank=True)),
                ('description', models.CharField(max_length=255, verbose_name=b'Description of Contribution', blank=True)),
                ('in_logframe', models.BooleanField(default=None, verbose_name=b'Is this Indicator in the Logframe?')),
                ('create_date', models.DateTimeField(null=True, blank=True)),
                ('edit_date', models.DateTimeField(null=True, blank=True)),
            ],
            options={
                'ordering': ('description',),
            },
            bases=(models.Model,),
        ),
        migrations.RemoveField(
            model_name='projectcompletion',
            name='cluster',
        ),
        migrations.RemoveField(
            model_name='projectcompletion',
            name='country',
        ),
        migrations.RemoveField(
            model_name='projectcompletion',
            name='district',
        ),
        migrations.RemoveField(
            model_name='projectcompletion',
            name='program',
        ),
        migrations.RemoveField(
            model_name='projectcompletion',
            name='project_agreement',
        ),
        migrations.RemoveField(
            model_name='projectcompletion',
            name='project_proposal',
        ),
        migrations.RemoveField(
            model_name='projectcompletion',
            name='province',
        ),
        migrations.RemoveField(
            model_name='projectcompletion',
            name='village',
        ),
        migrations.AddField(
            model_name='projectcomplete',
            name='qualitative_outputs',
            field=models.ForeignKey(to='programdb.QuantitativeOutputs'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='projectcomplete',
            name='reviewed_by',
            field=models.ForeignKey(related_name='reviewing_complete', blank=True, to=settings.AUTH_USER_MODEL, null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='projectcomplete',
            name='village',
            field=models.ForeignKey(blank=True, to='programdb.Village', null=True),
            preserve_default=True,
        ),
        migrations.RemoveField(
            model_name='projectagreement',
            name='field_office',
        ),
        migrations.RemoveField(
            model_name='projectagreement',
            name='project_code',
        ),
        migrations.RemoveField(
            model_name='projectproposal',
            name='project_code',
        ),
        migrations.AddField(
            model_name='projectagreement',
            name='activity_code',
            field=models.CharField(max_length=255, null=True, verbose_name=b'Activity Code', blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='projectagreement',
            name='office_code',
            field=models.CharField(max_length=255, null=True, verbose_name=b'Office Code', blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='projectproposal',
            name='activity_code',
            field=models.CharField(max_length=255, null=True, verbose_name=b'Activity Code', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='mergemap',
            name='project_completion',
            field=models.ForeignKey(to='programdb.ProjectComplete', null=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='programdashboard',
            name='project_agreement',
            field=models.ForeignKey(blank=True, to='programdb.ProjectAgreement', null=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='programdashboard',
            name='project_completion',
            field=models.ForeignKey(blank=True, to='programdb.ProjectComplete', null=True),
            preserve_default=True,
        ),
        migrations.DeleteModel(
            name='ProjectCompletion',
        ),
        migrations.AlterField(
            model_name='programdashboard',
            name='project_proposal',
            field=models.ForeignKey(blank=True, to='programdb.ProjectProposal', null=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='projectagreement',
            name='account_code',
            field=models.CharField(max_length=255, null=True, verbose_name=b'Account Code', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='projectagreement',
            name='beneficiary_type',
            field=models.CharField(max_length=255, null=True, verbose_name=b'Type of direct beneficiaries', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='projectagreement',
            name='cod_num',
            field=models.CharField(max_length=255, null=True, verbose_name=b'Project COD #', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='projectagreement',
            name='community',
            field=models.CharField(max_length=255, null=True, verbose_name=b'Community', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='projectagreement',
            name='community_mobilizer',
            field=models.CharField(max_length=255, null=True, verbose_name=b'Community Mobilizer', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='projectagreement',
            name='community_rep',
            field=models.CharField(max_length=255, null=True, verbose_name=b'Community Representative', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='projectagreement',
            name='community_rep_contact',
            field=models.CharField(max_length=255, null=True, verbose_name=b'Community Representative Contact', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='projectagreement',
            name='description_of_community_involvement',
            field=models.TextField(null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='projectagreement',
            name='description_of_government_involvement',
            field=models.TextField(null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='projectagreement',
            name='description_of_project_activities',
            field=models.TextField(null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='projectagreement',
            name='effect_or_impact',
            field=models.TextField(null=True, verbose_name=b'What is the anticipated effect of impact of this project?', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='projectagreement',
            name='estimation_date',
            field=models.DateTimeField(null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='projectagreement',
            name='expected_end_date',
            field=models.DateTimeField(null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='projectagreement',
            name='expected_start_date',
            field=models.DateTimeField(null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='projectagreement',
            name='justification_background',
            field=models.TextField(null=True, verbose_name=b'General background and problem statement', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='projectagreement',
            name='justification_description_community_selection',
            field=models.TextField(null=True, verbose_name=b'Description of community selection criteria', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='projectagreement',
            name='mc_estimated_budget',
            field=models.CharField(max_length=255, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='projectagreement',
            name='mc_objectives',
            field=models.TextField(null=True, verbose_name=b'What MC strategic Objectives does this help fulfill?', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='projectagreement',
            name='name_of_partners',
            field=models.CharField(max_length=255, null=True, verbose_name=b'Name of Partners', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='projectagreement',
            name='num_direct_beneficiaries',
            field=models.CharField(max_length=255, null=True, verbose_name=b'Number of direct beneficiaries', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='projectagreement',
            name='other_budget',
            field=models.CharField(max_length=255, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='projectagreement',
            name='partners',
            field=models.CharField(max_length=255, null=True, verbose_name=b'Partners', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='projectagreement',
            name='profile_code',
            field=models.CharField(max_length=255, null=True, verbose_name=b'Profile Code', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='projectagreement',
            name='program_objectives',
            field=models.TextField(null=True, verbose_name=b'What Program Objectives does this help fulfill?', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='projectagreement',
            name='project_activity',
            field=models.CharField(max_length=255, null=True, verbose_name=b'Project Activity', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='projectagreement',
            name='project_title',
            field=models.CharField(max_length=255, null=True, verbose_name=b'Project Title', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='projectagreement',
            name='project_type',
            field=models.CharField(max_length=255, null=True, verbose_name=b'Proposal Number', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='projectagreement',
            name='prop_status',
            field=models.CharField(max_length=255, null=True, verbose_name=b'Proposal Status', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='projectagreement',
            name='proposal_num',
            field=models.CharField(max_length=255, null=True, verbose_name=b'Proposal Number', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='projectagreement',
            name='rej_letter',
            field=models.TextField(null=True, verbose_name=b'Rejection Letter', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='projectagreement',
            name='sector',
            field=models.ForeignKey(blank=True, to='programdb.Sector', null=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='projectagreement',
            name='staff_responsible',
            field=models.CharField(max_length=255, null=True, verbose_name=b'MC Staff Responsible', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='projectagreement',
            name='sub_code',
            field=models.CharField(max_length=255, null=True, verbose_name=b'Account Sub Code', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='projectagreement',
            name='total_estimated_budget',
            field=models.CharField(max_length=255, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='projectproposal',
            name='approval',
            field=models.BooleanField(default=None, verbose_name=b'Approval'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='projectproposal',
            name='approval_remarks',
            field=models.CharField(max_length=255, null=True, verbose_name=b'Approval Remarks', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='projectproposal',
            name='community_mobilizer',
            field=models.CharField(max_length=255, null=True, verbose_name=b'Community Mobilizer', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='projectproposal',
            name='community_rep',
            field=models.CharField(max_length=255, null=True, verbose_name=b'Community Representative', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='projectproposal',
            name='community_rep_contact',
            field=models.CharField(max_length=255, null=True, verbose_name=b'Community Representative Contact', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='projectproposal',
            name='device_id',
            field=models.CharField(max_length=255, null=True, verbose_name=b'Device ID', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='projectproposal',
            name='meta_instance_id',
            field=models.CharField(max_length=255, null=True, verbose_name=b'Meta Instance ID', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='projectproposal',
            name='meta_instance_name',
            field=models.CharField(max_length=255, null=True, verbose_name=b'Meta Instance Name', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='projectproposal',
            name='odk_id',
            field=models.CharField(max_length=255, null=True, verbose_name=b'ODK ID', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='projectproposal',
            name='odk_index',
            field=models.CharField(max_length=255, null=True, verbose_name=b'ODK Index', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='projectproposal',
            name='odk_notes',
            field=models.CharField(max_length=255, null=True, verbose_name=b'ODK Notes', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='projectproposal',
            name='odk_parent_table_name',
            field=models.CharField(max_length=255, null=True, verbose_name=b'ODK Table Name', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='projectproposal',
            name='odk_tags',
            field=models.CharField(max_length=255, null=True, verbose_name=b'ODK Tags', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='projectproposal',
            name='odk_uuid',
            field=models.CharField(max_length=255, null=True, verbose_name=b'ODK UUID', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='projectproposal',
            name='profile_code',
            field=models.CharField(max_length=255, null=True, verbose_name=b'Profile Code', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='projectproposal',
            name='project_description',
            field=models.TextField(null=True, verbose_name=b'Project Description', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='projectproposal',
            name='project_title',
            field=models.CharField(max_length=255, verbose_name=b'Project Title'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='projectproposal',
            name='project_type',
            field=models.CharField(max_length=255, null=True, verbose_name=b'Proposal Number', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='projectproposal',
            name='prop_status',
            field=models.CharField(max_length=255, null=True, verbose_name=b'Proposal Status', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='projectproposal',
            name='proposal_num',
            field=models.CharField(max_length=255, null=True, verbose_name=b'Proposal Number', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='projectproposal',
            name='rej_letter',
            field=models.TextField(null=True, verbose_name=b'Rejection Letter', blank=True),
            preserve_default=True,
        ),
    ]
